### ISSUE TITLE
Get an illegal Stateexception from Ceilands

### ISSUE THREAD

**Issue by suerion** [Kitteh6660/Ceilands#10]
Here is the issue -> 

https://mclo.gs/uxspB63

```
[13:01:56] [main/WARN]: Failed to load datapacks, can't proceed with server load. You can either fix your datapacks or reset to vanilla with --safeMode
java.util.concurrent.ExecutionException: java.lang.IllegalStateException:

===== An error occurred loading registries =====

Registry 'minecraft:worldgen/biome':

Parsing Error: Not a JSON object: null missed input: {"creature":[{"type":"minecraft:pig","maxCount":4,"minCount":2,"weight":20},{"type":"minecraft:cow","maxCount":4,"minCount":2,"weight":20},{"type":"minecraft:sheep","maxCount":4,"minCount":2,"weight":20},{"type":"minecraft:chicken","maxCount":4,"minCount":2,"weight":20},{"type":"minecraft:horse","maxCount":2,"minCount":1,"weight":3},{"type":"minecraft:rabbit","maxCount":4,"minCount":2,"weight":6},{"type":"minecraft:sniffer","maxCount":1,"minCount":1,"weight":1},null]}
  at 'spawners'
  at 'ceilands:worldgen/biome/luzawood_forest' defined in 'ceilands'

-----

        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
        at net.minecraft.server.Main.main(Main.java:229) [server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.5.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.5.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.5.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.5.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.21.1-loader.0.16.5-launcher.1.0.1.jar:1.0.1]
Caused by: java.lang.IllegalStateException:

===== An error occurred loading registries =====

Registry 'minecraft:worldgen/biome':

Parsing Error: Not a JSON object: null missed input: {"creature":[{"type":"minecraft:pig","maxCount":4,"minCount":2,"weight":20},{"type":"minecraft:cow","maxCount":4,"minCount":2,"weight":20},{"type":"minecraft:sheep","maxCount":4,"minCount":2,"weight":20},{"type":"minecraft:chicken","maxCount":4,"minCount":2,"weight":20},{"type":"minecraft:horse","maxCount":2,"minCount":1,"weight":3},{"type":"minecraft:rabbit","maxCount":4,"minCount":2,"weight":6},{"type":"minecraft:sniffer","maxCount":1,"minCount":1,"weight":1},null]}
  at 'spawners'
  at 'ceilands:worldgen/biome/luzawood_forest' defined in 'ceilands'

-----

        at com.alcatrazescapee.cyanide.core.RegistryLoader.load(RegistryLoader.java:108) ~[cyanide-fabric-1.21.1-5.0.0.jar:?]
        at MC/net.minecraft.registry.RegistryLoader.handler$ccf000$cyanide$loadAndReportErrors(RegistryLoader.java:1524) ~[server-intermediary.jar:?]
        at MC/net.minecraft.registry.RegistryLoader.loadFromResource(RegistryLoader.java) ~[server-intermediary.jar:?]
        at MC/net.minecraft.server.SaveLoading.loadDynamicRegistryManager(SaveLoading.java:62) ~[server-intermediary.jar:?]
        at MC/net.minecraft.server.SaveLoading.withRegistriesLoaded(SaveLoading.java:66) ~[server-intermediary.jar:?]
        at MC/net.minecraft.server.SaveLoading.load(SaveLoading.java:32) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.method_43612(Main.java:184) ~[server-intermediary.jar:?]
        at MC/net.minecraft.util.Util.waitAndApply(Util.java:1018) ~[server-intermediary.jar:?]
        at MC/net.minecraft.util.Util.waitAndApply(Util.java:1012) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.main(Main.java:182) ~[server-intermediary.jar:?]
        ... 5 more

```

**Comment by Kitteh6660** [comment]
What Minecraft and mod version? And which loader are you on?

Edit: Oh, on Fabric 1.21.1. I will have to look into it!

**Comment by suerion** [comment]
Oh sorry, i'm on Fabric 1.21.1 with 0.16.5 loader and fabric api 0.105.0

I'm using cyanide for registry errors, thats the issue from cyanide.

Without i could start the server.

It is an dev enviroment, to fix issues on the server side.

If you need an log, i will come with it later

**Comment by suerion** [comment]
Thats cyanide

https://modrinth.com/mod/cyanide

**Comment by Kitteh6660** [comment]
Thank you, I found the offending json error and it will be resolved with next update.

**Comment by suerion** [comment]
> Thank you, I found the offending json error and it will be resolved with next update.

Sorry, had sendet the last answer with E-mail. Thanks for your work :)

**Comment by Kitteh6660** [comment]
It's no problem. I've uploaded a new version 0.7 for 1.21.1, does that fix the issue?

**Comment by suerion** [comment]
Hey, i will look today on it, i'm yet on work and will look later. :) thanks :)

**Comment by suerion** [comment]
Uh i had forgottrn to close the issue, thanks, it work now without issues
