### ISSUE TITLE
Entrypoint "main" provided "ceilands" Exception  [Fabric 1.21.1 on 0.16.9]

### ISSUE THREAD

**Issue by suerion** [Kitteh6660/Ceilands#11]
HEy, on newest update i get this issue on Starting the Server? Could you look on it?

Thanks a lot
Latest log
https://mclo.gs/M9wzjqs
```
[20:25:56 ERROR] [main]: [Main] Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'ceilands' at 'com.kittehmod.ceilands.fabric.fabric.CeilandsModFabric'!
        at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.16.9.jar:?]
        at knot/net.minecraft.server.Main.main(Main.java:111) [server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.21.1-loader.0.16.9-launcher.1.0.1.jar:1.0.1]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_2517
        at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027) ~[?:?]
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.9.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at knot/com.kittehmod.ceilands.fabric.registry.ModRegistryHandler.registerBlocks(ModRegistryHandler.java:62) ~[Ceilands-QuiFabrge-1.19.2-0.7.1.jar:?]
        at knot/com.kittehmod.ceilands.fabric.registry.ModRegistryHandler.registerModContent(ModRegistryHandler.java:32) ~[Ceilands-QuiFabrge-1.19.2-0.7.1.jar:?]
        at knot/com.kittehmod.ceilands.fabric.fabric.CeilandsRegistry.initializeRegistry(CeilandsRegistry.java:33) ~[Ceilands-QuiFabrge-1.19.2-0.7.1.jar:?]
        at knot/com.kittehmod.ceilands.fabric.fabric.CeilandsModFabric.onInitialize(CeilandsModFabric.java:15) ~[Ceilands-QuiFabrge-1.19.2-0.7.1.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.9.jar:?]
        ... 7 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_2517
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.9.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027) ~[?:?]
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.9.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at knot/com.kittehmod.ceilands.fabric.registry.ModRegistryHandler.registerBlocks(ModRegistryHandler.java:62) ~[Ceilands-QuiFabrge-1.19.2-0.7.1.jar:?]
        at knot/com.kittehmod.ceilands.fabric.registry.ModRegistryHandler.registerModContent(ModRegistryHandler.java:32) ~[Ceilands-QuiFabrge-1.19.2-0.7.1.jar:?]
        at knot/com.kittehmod.ceilands.fabric.fabric.CeilandsRegistry.initializeRegistry(CeilandsRegistry.java:33) ~[Ceilands-QuiFabrge-1.19.2-0.7.1.jar:?]
        at knot/com.kittehmod.ceilands.fabric.fabric.CeilandsModFabric.onInitialize(CeilandsModFabric.java:15) ~[Ceilands-QuiFabrge-1.19.2-0.7.1.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.9.jar:?]
        ... 7 more
```

**Comment by Kitteh6660** [comment]
You're using the wrong version of the mod. The one you're using is marked for 1.19.2.

**Comment by suerion** [comment]
@Kitteh6660 

looked on Modrinth, thats why i had added it, then there are only issued tags

i had thougt, it would be the false version, but had tryed because the tags are there

![image](https://github.com/user-attachments/assets/eeb618a1-17a4-4e7e-ab6c-a38a15ffa456)

**Comment by Kitteh6660** [comment]
Must be Modrinth being derped and insisting on adding the wrong versions. I corrected the versions on Modrinth.

**Comment by suerion** [comment]
0.7 works fine for me on fabric, thanks to clearify this issue
